name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '32 4 1-31/2 * *'


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        run: |
          npm i


      - name: Get remote caches
        run: |
          curl --location --remote-name https://storage.gmodwiki.com/build_cache.zip
          unzip build_cache.zip
          rm -v build_cache.zip

          curl --location --remote-name https://storage.gmodwiki.com/public_cache.zip
          unzip public_cache.zip
          rm -v public_cache.zip

      - name: Remove expired files
        run: |
          npm run clear_recent_changes


      - name: Scrape and Build
        env:
          BUILD_ENV: production
        run: |
          npm run build


      - name: Upload search index
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: r2 object put gmodwiki/search_index.json --file ./public/search_index.json


      - name: Build final pack
        env:
          BUILD_ENV: production
        run: |
          # Temporarily move it out of the public dir to keep it out of the Cloudflare bundle
          mv --verbose ./public/search_index.json .
          npm run astrobuild


      # Remote cache
      - name: Prepare remote cache files
        run: |
          zip --recurse-paths -9 --quiet public_cache.zip ./public
          zip --recurse-paths -9 --quiet build_cache.zip ./build/cache

      - name: Upload public cache
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: r2 object put gmodwiki/public_cache.zip --file ./public_cache.zip

      - name: Upload build cache
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: r2 object put gmodwiki/build_cache.zip --file ./build_cache.zip

      - name: Remove build caches
        run: |
          rm -v public_cache.zip build_cache.zip


      # CF Publish
      - name: Publish Site
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy --project-name=gmodwiki ./dist

      - name: Clear CF Cache
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CLOUDFLARE_CACHE_API_KEY: ${{ secrets.CF_CACHE_API_TOKEN }}
        run: |
          npm run clear_cloudflare_cache
          rm deleted_files.txt


      # Docker
      # This only deploys on Monday if it was a scheduled run
      # It always deploys for manual runs
      - name: Build starter image
        if: ${{ github.event_name != 'schedule' || (format('{{date:u}}')) == '1' }}
        run: |
          mv --verbose ./search_index.json ./public/
          docker build --tag ghcr.io/cfc-servers/gmodwiki:latest .

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'schedule' || (format('{{date:u}}')) == '1' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Tag and push image
        if: ${{ github.event_name != 'schedule' || (format('{{date:u}}')) == '1' }}
        run: |
          docker push ghcr.io/cfc-servers/gmodwiki --all-tags

