on:
  workflow_dispatch:
  schedule:
    - cron: '32 4 1-31/3 * *'


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        run: |
          npm i

      - name: Build
        run: |
          npm run build
          npx astro build

      - name: Publish
        uses: cloudflare/wrangler-action@3.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy --project-name=gmodwiki ./dist
