name: Release

on:
  workflow_dispatch:
    inputs:
      build_container:
        type: boolean
        description: "Should this build also build a new Docker image"
  schedule:
    - cron: '32 4 1-31/2 * *'


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        run: |
          npm i
          npm i wrangler@3.13.2


      - name: Get remote caches
        run: |
          (curl --location --remote-name https://storage.gmodwiki.com/build_cache.zip && unzip -q build_cache.zip) &
          (curl --location --remote-name https://storage.gmodwiki.com/public_cache.zip && unzip -q public_cache.zip) &

          wait

          rm -v build_cache.zip public_cache.zip

      - name: Remove expired files
        run: |
          npm run clear_recent_changes


      - name: Scrape and Build
        env:
          BUILD_ENV: production
        run: |
          npm run build


      - name: Upload search index
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npx wrangler r2 object put gmodwiki/search_index.json --file ./public/search_index.json


      - name: Build final pack
        env:
          BUILD_ENV: production
        run: |
          # Temporarily move it out of the public dir to keep it out of the Cloudflare bundle
          mv --verbose ./public/search_index.json .
          npm run astrobuild


      # Remote cache
      - name: Prepare remote cache files
        run: |
          zip --recurse-paths -9 --quiet public_cache.zip ./public &
          zip --recurse-paths -9 --quiet build_cache.zip ./build/cache &
          wait

      - name: Upload cache packages
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npx wrangler r2 object put gmodwiki/public_cache.zip --file ./public_cache.zip &
          npx wrangler r2 object put gmodwiki/build_cache.zip --file ./build_cache.zip &

          wait

          rm -v public_cache.zip build_cache.zip


      # CF Publish
      - name: Publish Site
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npx wrangler pages deploy --project-name=gmodwiki ./dist

      - name: Clear CF Cache
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CLOUDFLARE_CACHE_API_KEY: ${{ secrets.CF_CACHE_API_TOKEN }}
        run: |
          npm run clear_cloudflare_cache
          rm deleted_files.json


      # Docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build & Push Docker Image
        if: ${{ (github.event_name == 'schedule' && (format('{{date:u}}')) == '1') || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_container == 'true') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/cfc-servers/gmodwiki:latest
